### ISSUE TITLE
Dependency issue in Ubuntu 18.04

### ISSUE THREAD

**Issue by eddygta17** [udacity/CppND-Memory-Management-Chatbot#11]
The Readme is old.

These are the packages available in Ubuntu 18.04,
$ apt-cache search libwxgt*

libwxgtk-media3.0-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK+ media library runtime)
libwxgtk-media3.0-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK+ media library development)
libwxgtk-media3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 media library runtime)
libwxgtk-media3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 media library development)
libwxgtk-webview3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 webview library runtime)
libwxgtk-webview3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 webview library development)
libwxgtk3.0-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
libwxgtk3.0-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK+ development)
libwxgtk3.0-gtk3-0v5 - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 runtime)
libwxgtk3.0-gtk3-dev - wxWidgets Cross-platform C++ GUI toolkit (GTK+ 3 development)

**Comment by robinloujun** [comment]
I am for the issue, under Ubuntu 18.04 the dependencies for wxWidgets should be installed with
```
sudo apt-get install libwxgtk3.0-dev libwxgtk3.0-0v5
```

**Comment by 47krishnaveersingh** [comment]
yeah the READme is old the package name too are changed and dbg is not availabel for ubuntu 20.04 focal so  
 you should intall wxwidget dependencies from here as by official wx widgets
follow the instructions on the page:-
[link](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets30Binaries#toc2)

**Comment by xmnlab** [comment]
any recommendation for ubuntu 20.10? 

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libwxgtk3.0-dev : Depends: wx3.0-headers (= 3.0.5-1.focal) but 3.0.5.1+dfsg-2 is to be installed
                   Depends: libwxbase3.0-dev (= 3.0.5-1.focal) but 3.0.5.1+dfsg-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by SudKul** [comment]
Thank you @xmnlab @robinloujun @eddygta17 @47krishnaveersingh for flagging this to us. 
We have [updated](https://github.com/udacity/CppND-Memory-Management-Chatbot/commit/c0144079d23b8c5622c3c943dee701a84bbf2935) the README file.
