### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by akutschi** [udacity/CppND-Memory-Management-Chatbot#5]
What license does this project have? Another CppND project is MIT licensed but this repository does not have any license information.

**Comment by SudKul** [comment]
Hey @akutschi 
Thank you, for flagging this issue. It's **Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)**.

The [license file](https://github.com/udacity/CppND-Memory-Management-Chatbot/blob/master/LICENSE) now available in the repo. 
Thanks 👍
